# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba06689fd4fcb280e8e9135af8e40f05a94c289e2ef0b317f38842d0eb567ab6dc743403b373c2302afd2a2c78bfb939cf87a9ce4dcdc5aefacb6d6980493c5

test:
  secret_key_base: 1b6b311fb2a5c5163d99dc46bdc1bafeb351fe6802fc45f60917ecdf90e9df1d212ad4259c97c39c97350c61e6b5fa3b17a4c60ec82e1a690c84ea7f470056a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
